### ISSUE TITLE
Test suite spawns interactive shell under FreeBSD

### ISSUE THREAD

**Issue by eserte** [powerman/migrate#1]
On FreeBSD systems, t/example.t seems to spawn interactive shells. I have to manually enter "exit" a couple of times to finish the test.

It also seems that tests fail in different ways also on other non-Linux platforms, see http://matrix.cpantesters.org/?dist=App-migrate+v0.1.1

**Comment by powerman** [comment]
Thanks, I've already noticed this. But looks like I've to install FreeBSD in VirtualBox first, to be able to fix tests on *bsd.

**Comment by powerman** [comment]
Fixed in v0.1.2.
