### ISSUE TITLE
CPAN Testers: Non-zero wait status: 9

### ISSUE THREAD

**Issue by powerman** [powerman/migrate#3]
@eserte Can I do anything to avoid issues like http://www.cpantesters.org/cpan/report/4dd4f1b4-df84-11e5-befb-a41bfdd2507e (also I've similar report for another perl module http://www.cpantesters.org/cpan/report/60c631ee-df79-11e5-bbca-77f3fcd2507e)? Or these errors means my tests was killed with SIGKILL because of some internal issue on host system (like kernel OOM killer or something like this) and I just can't have a "green matrix"?

**Comment by eserte** [comment]
The wallclock value is the interesting one:

```
Files=6, Tests=77, 4582 wallclock secs ( 0.05 usr  0.04 sys +  0.27 cusr  0.11 csys =  0.47 CPU)
```

Obviously the t/example.t test was hanging. Earlier versions also have this problem, see http://www.cpantesters.org/cpan/report/6977e5d0-d5ba-11e5-829d-9fa7fcd2507e

So maybe some kind of race condition? I tried to run t/example.t in a loop to see if it is reproducible. However, I got a test error after about 100 iterations. Maybe this one is related?

```
    # Subtest: 0.2.0 <-> 1.0.0
    ok 1 - 0.2.0 -> 1.0.0
    ok 2 - ... ./some_daemon exists
    not ok 3 - ... some_daemon is running
    #   Failed test '... some_daemon is running'
    #   at t/example.t line 122.
    #          got: '256'
    #     expected: '0'
    ok 4 - 1.0.0 -> 0.2.0
    ok 5 - ... some_daemon is not running
    ok 6 - ... ./some_daemon does not exists
    1..6
    # Looks like you failed 1 test of 6.
not ok 5 - 0.2.0 <-> 1.0.0
#   Failed test '0.2.0 <-> 1.0.0'
#   at t/example.t line 134.
```

**Comment by eserte** [comment]
... and now I got something which is probably causing the hanging test. The last test output looks like:

```
ok 4 - 0.1.0 <-> 0.2.0
    # Subtest: 0.2.0 <-> 1.0.0
    ok 1 - 0.2.0 -> 1.0.0
    ok 2 - ... ./some_daemon exists
    not ok 3 - ... some_daemon is running
    #   Failed test '... some_daemon is running'
    #   at t/example.t line 122.
    #          got: '256'
    #     expected: '0'
```

and the test script apparently stopped and an unusable shell appears (unusable, because every input is apparently ignored). pstree shows:

```
      `-perl,15956 /home/cpansand/bin/sh/forever -e -0.001 perl5.20.0 -Mblib t/example.t
          `-perl5.20.0,16295 -Mblib t/example.t
              `-zsh,16314
```

And perl-stacktrace:

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f284868fa3e in __libc_waitpid (pid=<optimized out>, stat_loc=0x7fffd6f4d9a8, options=<optimized out>) at ../sysdeps/unix/sysv/linux/waitpid.c:32
32      ../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
t/example.t:134
/opt/perl-5.20.0/lib/site_perl/5.20.0/Test/More.pm:771
/opt/perl-5.20.0/lib/site_perl/5.20.0/Test/Builder.pm:266
/opt/perl-5.20.0/lib/site_perl/5.20.0/Test/Builder.pm:266
/opt/perl-5.20.0/lib/site_perl/5.20.0/Test/Builder.pm:261
t/example.t:125
t/example.t:163
/opt/perl-5.20.0/lib/site_perl/5.20.0/Test/Exception.pm:302
/opt/perl-5.20.0/lib/site_perl/5.20.0/Test/Exception.pm:141
/opt/perl-5.20.0/lib/site_perl/5.20.0/Test/Exception.pm:141
/opt/perl-5.20.0/lib/site_perl/5.20.0/Sub/Uplevel.pm:87
t/example.t:160
/opt/perl-5.20.0/lib/site_perl/5.20.0/Test/Output.pm:872
/opt/perl-5.20.0/lib/site_perl/5.20.0/Capture/Tiny.pm:382
/opt/perl-5.20.0/lib/site_perl/5.20.0/Capture/Tiny.pm:382
/opt/perl-5.20.0/lib/site_perl/5.20.0/Test/Output.pm:871
t/example.t:159
/tmpfs/.cpan-build-cpansand/2016030506/App-migrate-v0.2.4-o905Mz/blib/lib/App/migrate.pm:180
/tmpfs/.cpan-build-cpansand/2016030506/App-migrate-v0.2.4-o905Mz/blib/lib/App/migrate.pm:172
/tmpfs/.cpan-build-cpansand/2016030506/App-migrate-v0.2.4-o905Mz/blib/lib/App/migrate.pm:233
```

**Comment by powerman** [comment]
Well… this doesn't really helps. :disappointed: 

Here is what is test does at that point:
- Everything happens in temporary directory (created by Path::Tiny::tempdir).
- Test creates file `some_daemon` with this contents:

``` sh
#!/bin/sh
kill -STOP $$
```
- (this is done by executing `patch -E <0.2.0.patch >/dev/null` with this contents in `0.2.0.patch`)

``` diff
diff -uNr some_daemon some_daemon
--- some_daemon 1970-01-01 03:00:00.000000000 +0300
+++ some_daemon 2015-02-24 06:34:47.321969399 +0200
@@ -0,0 +1,2 @@
+#!/bin/sh
+kill -STOP $$
```
- Next it executes `rm -f *.orig` and `chmod +x some_daemon`
- Then it runs that script by executing `./some_daemon &`
- Now it tries to check is everything is ok by executing `pgrep -x -f "/bin/sh ./some_daemon" >/dev/null`
  - this test is disabled on CPAN Testers because of race condition (I suppose sometimes it executes `system('./some_daemon &');` and then `system('pgrep -x -f "/bin/sh ./some_daemon" >/dev/null')` faster than some_daemon actually starts and initialize ARGV[0] with "/bin/sh ./some_daemon").
    - **THIS IS FAILED TEST**

Now test tries to undo all of these:
- It tries to kill some_daemon process by executing `pkill -9 -x -f '/bin/sh ./some_daemon'` and remove file by reversing patch: `patch -E -R <0.2.0.patch >/dev/null` and `rm -f *.orig`
  - **IT HANGS HERE!**
- Now it tries to check is everything is ok by executing `pgrep -x -f "/bin/sh ./some_daemon" >/dev/null`
  - this test is disabled on CPAN Testers because of similar race condition

It looks like hang somehow related to reason why previous test fails, i.e executing `./some_daemon &` doesn't works (or works too slowly). But I still don't see why and how it may hang because of this, especially if there are no `pkill` or `patch` processes left, only shell…

I've just did 1000 runs of that test on my workstation - no errors and no hangs. But I noticed I'm using bash, while you're using zsh.

@eserte Do you've any ideas about how to fix/debug this, or should I just disable this test completely on CPAN Testers?

**Comment by powerman** [comment]
Actually forget about this, I've realized what happens - it doesn't hangs, it run "emergency shell" asking user to interactively fix something - that's what that running zsh does. I'll disable it in test and this issue should be fixed. Thanks!
